### ISSUE TITLE
Type covariant requirement

### ISSUE THREAD

**Issue by marcospassos** [mindplay-dk/php-generics-rfc#24]
First of all, many thanks for expending such time and effort to bring generics to PHP. 

Generics and type covariance are the two most import OOP concepts still missing in PHP. But, how to introduce Generics when we don't have support to type covariance yet? 

Supporting only one of these features introduces design inconsistencies, as shown in the following example:

```php
class Letter {}
class A extends Letter {} 
class B extends Letter {}

class Builder<T is Letter> {
	public function build() : T;
}

interface Factory {
	public function create() : Letter;
}

class AFactory implements Factory {
	// Currently unsupported
	public function create() : A;
}
```

**Comment by natebrunette** [comment]
We're currently operating under the assumption that co/contravariance will be added to PHP before generics.

**Comment by marcospassos** [comment]
There is a long discussion about how to introduce support to type covariance, due to issues related to auto-loading. So it's still an unresolved issue that needs to be addressed.

**Comment by morrisonlevi** [comment]
Generics do not require covariance and contravariance but they definitely become more useful with it. Return type covariance is actively being worked on too.
