### ISSUE TITLE
Alternative ways to contribute

### ISSUE THREAD

**Issue by marcospassos** [mindplay-dk/php-generics-rfc#25]
Although I do not have enough skills in C to provide PR, I would really like to contribute in some way to help to bring support for generic programming in PHP.

So, how about a crowdfunding campaign to raise funds to pay a developer? The big issue IMHO is the lack of guarantees that the functionality will be accepted as part of the core by the PHP maintainers, once implemented.

**Comment by morrisonlevi** [comment]
How does anyone even ensure that things like that get paid out to the correct people?

**Comment by natebrunette** [comment]
I'm not sure. I assume the bounty gets paid out to the submitter. I didn't start working on this for the bounty; hopefully we can just figure out an equitable way to split it.

**Comment by mindplay-dk** [comment]
I'd like to forfeit any claim to my share of $1,000 - the conversion fee alone would eat it up 😂 

I don't think anyone's doing this for the money.

Anyone opposed to closing this meta-issue?

**Comment by marcospassos** [comment]
👍
