### ISSUE TITLE
Class definitions (generic/non-generic)

### ISSUE THREAD

**Issue by natebrunette** [mindplay-dk/php-generics-rfc#26]
Can `class Box {}` and `class Box<T> {}` exist in the same namespace? Is this a duplicate class declaration error?

**Comment by morrisonlevi** [comment]
This is a duplicate definition, right? This is why we care about having default type parameters for the built-in interfaces such as `ArrayAccess<Key = mixed, Value = mixed>`.

**Comment by natebrunette** [comment]
My assumption was that it would be a duplicate. We should make that clear in the rfc.

**Comment by mindplay-dk** [comment]
The class-name of either `class Box {}` or `class Box<T> {}` are both `"Box"`.

The filename would be `"Box.php"` in either case, and I think we settled on `get_class($box)` returning `"Box"` in either case, so I think it kind of goes without saying?

I suppose one *could* technically cram two conflicting definitions in one file, something like:

```php
namespace Foo {
  class Box {}
  class Box<T> {}
}
```

In my opinion, this should just result in the usual fatal error:

    Fatal error: Cannot declare class Box, because the name is already in use

I think this is sufficiently covered by the RFC:

```
Note that type arguments are internally reified, and can be accessed via reflection, but are not a part of the type-name:

<code php>
var_dump(get_class($entry)); // => (string) "Entry"
</code>
```

@natebrunette if you think this needs further clarification, feel free to make changes :-)
