### ISSUE TITLE
Static type constraint

### ISSUE THREAD

**Issue by marcospassos** [mindplay-dk/php-generics-rfc#28]
There are some use cases for specifying that a type must be a subtype of the concrete class, as shown in the following example:

```php
interface Equatable<T instanceof static> {
     public function equals(T $other) : bool;
}

interface Comparable<T instanceof static> {
     public function compareTo(T $other) : int;
}
```
Are there any plans for supporting such feature? I did not find any topic about `static` in the RFC.

**Comment by mindplay-dk** [comment]
How is this functionally different from:

```php
interface Comparable<T> {
     public function compareTo(static $other) : int;
}
```

The type-constraint `<T instanceof static>` doesn't result in any constraint or type-check, does it? It seems to basically say, "T is whatever you've implemented", which doesn't sound like a constraint on T - how would you expect this to be type-checked?

**Comment by marcospassos** [comment]
You're right. The `static` return type is perfectly fine and would be a good addition to PHP's core IMHO as it is fundamentally a type covariance:

```php
interface Number {
    public function plus(Number $addend) : static
}
```
However, the same does not hold for function parameters, as it violates the Liskov Substitution Principle:

```php
class Number {
    public function plus(static $addend) : static {}
}

class Real extends Number {
    public function plus(Real $addend) : static {}
}

class Integer extends Real {
    // Does not match the signature of Real::plus
    public function plus(Integer $addend) : static {}
}
```

Thank you for highlighting the issue.
