### ISSUE TITLE
Resource Type

### ISSUE THREAD

**Issue by orolyn** [mindplay-dk/php-generics-rfc#31]
There is no `resource` type hint, and I don't expect there to be one in the near future. How would one instantiate an instance where a type argument needs to be a resource?

**Comment by morrisonlevi** [comment]
I don't understand the use-case or issue; could you elaborate?

**Comment by orolyn** [comment]
```
class Foo<T>
{
    public function __construct(T $var)
    {
    }
}

new Foo<???>(fopen('myfile.txt', 'r'));
```

**Comment by morrisonlevi** [comment]
Maybe warn and use `mixed`?
