### ISSUE TITLE
PHP 8?

### ISSUE THREAD

**Issue by BenMorel** [mindplay-dk/php-generics-rfc#47]
Hi, sorry if this is not the right place to ask, but I'm wondering if anybody has a plan to get generics into PHP 8? I understand that there must be a hell of a lot of work to get this done the right way, but as the deadline for RFCs is approaching, I thought I'd ask anyway!

**Comment by mindplay-dk** [comment]
I don't think we'd be able to answer all the questions on time.

There are gaps in the RFC itself that are difficult to close and likely more discussion, prototyping and testing is required before we'd arrive at a viable RFC.

I very much doubt it would pass a vote in it's current state.

**Comment by nikic** [comment]
I think it's safe to give a hard "no" on this as far as PHP 8.0 is concerned. No statement on 8.x.

**Comment by BenMorel** [comment]
Thank you for the feedback. Hopefully 8.x ! 🤞
